/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#000f22',
        'surface-container-low':    '#021c37',
        'surface-container':        '#06203b',
        'surface-container-high':   '#132b46',
        'surface-container-highest':'#1f3651',
        'surface-dim':              '#00142a',
        'surface':                  '#00142a',
        'surface-bright':           '#243a56',
        'surface-variant':          '#1f3651',
        'on-surface':               '#d3e4ff',
        'on-surface-variant':       '#e8bcb7',
        'inverse-surface':          '#d3e4ff',
        'inverse-on-surface':       '#1b314d',
        'background':               '#00142a',
        'on-background':            '#d3e4ff',
        'primary':                  '#ffb4ab',
        'on-primary':               '#690006',
        'primary-container':        '#ff544b',
        'on-primary-container':     '#5c0005',
        'primary-fixed':            '#ffdad6',
        'primary-fixed-dim':        '#ffb4ab',
        'on-primary-fixed':         '#410002',
        'on-primary-fixed-variant': '#93000d',
        'inverse-primary':          '#c00014',
        'secondary':                '#a2e7ff',
        'on-secondary':             '#003642',
        'secondary-container':      '#00d2fd',
        'on-secondary-container':   '#005669',
        'secondary-fixed':          '#b4ebff',
        'secondary-fixed-dim':      '#3cd7ff',
        'on-secondary-fixed':       '#001f27',
        'on-secondary-fixed-variant':'#004e5f',
        'tertiary':                 '#bec7d9',
        'on-tertiary':              '#28313f',
        'tertiary-container':       '#8991a2',
        'on-tertiary-container':    '#222a38',
        'tertiary-fixed':           '#dae3f6',
        'tertiary-fixed-dim':       '#bec7d9',
        'on-tertiary-fixed':        '#131c29',
        'on-tertiary-fixed-variant':'#3f4756',
        'error':                    '#ffb4ab',
        'on-error':                 '#690005',
        'error-container':          '#93000a',
        'on-error-container':       '#ffdad6',
        'outline':                  '#ae8783',
        'outline-variant':          '#5e3f3c',
        'surface-tint':             '#ffb4ab',
        'warning':                  '#fbbf24',
        'caution':                  '#f97316',
      },
      fontFamily: {
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'h1':         ['Space Grotesk', 'sans-serif'],
        'h2':         ['Space Grotesk', 'sans-serif'],
        'body-main':  ['Inter', 'sans-serif'],
        'body-strong':['Inter', 'sans-serif'],
        'data-mono':  ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1',  letterSpacing: '-0.02em', fontWeight: '700' }],
        'h1':         ['32px', { lineHeight: '1.2',  letterSpacing: '0.02em',  fontWeight: '600' }],
        'h2':         ['24px', { lineHeight: '1.3',  letterSpacing: '0.02em',  fontWeight: '600' }],
        'body-main':  ['16px', { lineHeight: '1.6',  letterSpacing: '0em',     fontWeight: '400' }],
        'body-strong':['16px', { lineHeight: '1.6',  letterSpacing: '0em',     fontWeight: '600' }],
        'data-mono':  ['14px', { lineHeight: '1.4',  letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-caps': ['11px', { lineHeight: '1',    letterSpacing: '0.1em',   fontWeight: '700' }],
      },
      spacing: {
        'unit':          '4px',
        'gutter':        '16px',
        'margin':        '24px',
        'container-max': '1440px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
}